<h1> Vectors, Matrices, and Arrays </h1>

# 0.0 Imports 

In [8]:
import numpy as np
from scipy import sparse

# 1.0 Introduction

## 1.1 Creating a Vector

In [2]:
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

In [10]:
vector_columns = np.array([[1],
                           [2],
                           [3]])
vector_columns

array([[1],
       [2],
       [3]])

## 1.2 Creating a Matrix 

In [11]:
matrix = np.array([[1,2],
                   [3,4],
                   [4,5]])
matrix

array([[1, 2],
       [3, 4],
       [4, 5]])

In [12]:
matrix_object = np.mat([[1,2],
                        [3,4],
                        [4,5]])
matrix_object

matrix([[1, 2],
        [3, 4],
        [4, 5]])

## 1.3 Sparse Matrix 

In [13]:
matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])

In [16]:
# A sparse matrix is a matrix that have just a few nonzero values
# Is possible to storage it more efficiently using the sparse  constructor from scipy lib
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [19]:
# It's a huge difference between the two representations in termos of storage
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_sparse)
print("")
print(matrix_large_sparse)
                         


  (1, 1)	1
  (2, 0)	3

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements 

In [35]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(vector[2])

print(matrix[1,1])

3
5


In [22]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [23]:
vector[:3]

array([1, 2, 3])

In [24]:
vector[3:]

array([4, 5, 6])

In [28]:
vector[-1]

6

In [33]:
vector[1:3]

array([2, 3])

In [36]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix 

In [43]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [44]:
matrix.shape

(3, 4)

In [45]:
matrix.size

12

In [46]:
matrix.ndim

2

## 1.6 Applying Operations to Elements 

In [47]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

add_100 = lambda i: i+100
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [48]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Finding the Maximum and Minimum Values 

In [49]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

np.max(matrix)

9

In [50]:
np.min(matrix)

1

In [51]:
np.max(matrix, axis = 0)

array([7, 8, 9])

In [52]:
np.max(matrix, axis = 1)

array([3, 6, 9])

##  1.8 Calculating the Average, Variance, and Standard Deviation

In [53]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [54]:
np.mean(matrix)

5.0

In [55]:
np.var(matrix)

6.666666666666667

In [56]:
np.std(matrix)

2.581988897471611

In [57]:
np.mean(matrix, axis = 0)

array([4., 5., 6.])

## 1.9 Reshaping Arrays 

In [63]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

In [61]:
matrix.shape

(4, 3)

In [62]:
matrix.size

12

In [60]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [64]:
matrix.reshape(1, -1) # -1 means "as many as needed"

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [65]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 Transposing a Vector or Matrix 

In [66]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [67]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [68]:
# In terms of linear algebra, a vector cannot be transposed, but it's "possible" with numpy
# at least, visually
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix 

In [70]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix.flatten() # transform a matrix into a one-dimensional array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 1.12 Finding the Rank of a Matrix

In [74]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant 

In [75]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix 

In [76]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
matrix.diagonal()

array([1, 4, 9])

In [77]:
# getting the other possible diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [78]:
matrix.diagonal(offset=-1)

array([2, 8])

## 1.15 Calculating the Trace of a Matrix 

In [79]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
matrix.trace() # return the sum along diagonals

14

In [80]:
sum(matrix.diagonal()) # do the same

14

## 1.16 Finding Eigenvalues and Eigenvectors 

In [81]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

In [84]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [85]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [86]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products 

In [87]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

np.dot(vector_a, vector_b)

32

In [88]:
vector_a @ vector_b # do the same

32

## 1.18 Adding and subtracting Matrices 

In [89]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

In [90]:
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [91]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [92]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [93]:
matrix_a + matrix_b # do the same

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matrices 

In [94]:
matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

## 1.20 Inverting a Matrix 

In [97]:
matrix = np.array([[1, 4],
                  [2, 5]])

np.linalg.inv(matrix) # the matrix that multiply the original to get the identity matrix

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## 1.21 Generating Random Values 

In [101]:
np.random.seed(0) # seed to always get the same random below

In [102]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [103]:
np.random.randint(0, 11, 3) # three random integers between 1 and 10

array([3, 7, 9])

In [105]:
np.random.normal(0, 1, 3) # 3 random numbers from normal distribution with mean 0.0

array([-0.13309028, -0.1730696 , -1.76165167])

In [106]:
np.random.uniform(1, 2, 3) # 3 random numbers from uniform distribution between 1 and 2

array([1.81216873, 1.47997717, 1.3927848 ])